rng0:
  build: rng

rng1:
  build: rng

rng2:
  build: rng

rng:
  image: jpetazzo/hamba
  links:
    - rng0
    - rng1
    - rng2
  command: 80 rng0:80 rng1:80 rng2:80
  ports:
    - "8001:80"

hasher:
  build: hasher
  ports:
    - "8002:80"

webui:
  build: webui
  links:
    - redis
  ports:
    - "8000:80"
  volumes:
    - "./webui/files/:/files/"

redis:
  image: redis

worker:
  build: worker
  links:
    - rng
    - hasher
    - redis
